import {
  Customer,
  Account,
  Transaction,
  Card,
  Statement,
  SupportTicket,
  FAQItem,
  InternalService,
  SystemDebugInfo,
} from './mockTypes';

export const mockCustomer: Customer = {
  id: 'VB-8940192',
  name: 'Bavana Sruthi',
  email: 'bavana.sruthi@vaultbank-client.in',
  phone: '+91 98765 43210',
  address: 'Suite 402, Financial Centre Tower, BKC, Mumbai, MH 400051',
  kycStatus: 'Verified',
  customerSince: 'November 2021',
  preferredBranch: 'BKC Corporate Branch, Mumbai',
  relationshipManager: 'Rohan Deshmukh (ID: RM-4491)',
  securityRating: 'Tier 1 Prime',
  lastLogin: 'Today at 10:14 AM IST from Chrome 128.0 (Windows 11)',
  activeDevicesCount: 3,
};

export const mockAccounts: Account[] = [
  {
    id: 'acc-01',
    accountNumber: '•••• •••• 4821',
    rawAccountNumber: '409210924821',
    type: 'Checking',
    name: 'Vault Premier Salary Checking',
    balance: 2482045.00,
    availableBalance: 2482045.00,
    currency: 'INR',
    status: 'Active',
    interestRate: '3.50% p.a.',
    ifscCode: 'VAUL0000409',
  },
  {
    id: 'acc-02',
    accountNumber: '•••• •••• 9104',
    rawAccountNumber: '409210929104',
    type: 'Savings',
    name: 'Vault High-Yield Super Savings',
    balance: 6824018.00,
    availableBalance: 6824018.00,
    currency: 'INR',
    status: 'Active',
    interestRate: '7.15% p.a.',
    ifscCode: 'VAUL0000409',
  },
  {
    id: 'acc-03',
    accountNumber: '•••• •••• 1150',
    rawAccountNumber: '409210921150',
    type: 'Fixed Deposit',
    name: 'Vault Guaranteed Tax Shield FD',
    balance: 1500000.00,
    availableBalance: 0.00,
    currency: 'INR',
    status: 'Active',
    interestRate: '8.25% p.a.',
    ifscCode: 'VAUL0000409',
  }
];

export const totalAvailableBalance = mockAccounts[0].availableBalance + mockAccounts[1].availableBalance; // ₹93,06,063.00

export const mockTransactions: Transaction[] = [
  {
    id: 'TXN-90284102',
    date: '2026-09-16',
    time: '09:42 AM',
    merchant: 'Infosys Tech Payroll Deposit',
    category: 'Salary',
    amount: 325000.00,
    type: 'credit',
    status: 'Completed',
    account: 'Vault Premier Salary Checking (•••• 4821)',
    senderRecipient: 'Infosys Ltd Treasury Account',
    referenceNumber: 'CMS90281048109',
    paymentMethod: 'NEFT / Direct Credit',
    location: 'Bengaluru, KA',
    notes: 'Monthly corporate executive remuneration',
  },
  {
    id: 'TXN-90284101',
    date: '2026-09-15',
    time: '07:15 PM',
    merchant: 'Taj Mahal Palace Fine Dining',
    category: 'Dining',
    amount: 18450.00,
    type: 'debit',
    status: 'Completed',
    account: 'Vault Premier Salary Checking (•••• 4821)',
    senderRecipient: 'Taj Hotels International',
    referenceNumber: 'POS-891049281',
    paymentMethod: 'Vault Metal Visa Infinite Card',
    location: 'Colaba, Mumbai',
  },
  {
    id: 'TXN-90284099',
    date: '2026-09-14',
    time: '02:30 PM',
    merchant: 'Zerodha Broking Ltd Auto Fund Transfer',
    category: 'Investment',
    amount: 150000.00,
    type: 'debit',
    status: 'Completed',
    account: 'Vault High-Yield Super Savings (•••• 9104)',
    senderRecipient: 'Zerodha Broking Escrow',
    referenceNumber: 'UPI/628104829104',
    paymentMethod: 'UPI Auto-Mandate',
    location: 'Mumbai, MH',
  },
  {
    id: 'TXN-90284095',
    date: '2026-09-12',
    time: '11:10 AM',
    merchant: 'Apple Store India Online',
    category: 'Shopping',
    amount: 139900.00,
    type: 'debit',
    status: 'Completed',
    account: 'Vault Premier Salary Checking (•••• 4821)',
    senderRecipient: 'Apple India Pvt Ltd',
    referenceNumber: 'INV-APL-904810',
    paymentMethod: 'Vault Metal Visa Infinite Card',
    location: 'Mumbai, MH',
  },
  {
    id: 'TXN-90284088',
    date: '2026-09-10',
    time: '04:55 PM',
    merchant: 'Tata Power Electricity Bill',
    category: 'Utilities',
    amount: 8420.00,
    type: 'debit',
    status: 'Completed',
    account: 'Vault Premier Salary Checking (•••• 4821)',
    senderRecipient: 'Tata Power Ltd Billing',
    referenceNumber: 'BBPS-910481092',
    paymentMethod: 'BillPay Direct Debit',
    location: 'Mumbai, MH',
  },
  {
    id: 'TXN-90284082',
    date: '2026-09-08',
    time: '01:15 PM',
    merchant: 'Interest Payout - High Yield Savings',
    category: 'Salary',
    amount: 39820.00,
    type: 'credit',
    status: 'Completed',
    account: 'Vault High-Yield Super Savings (•••• 9104)',
    senderRecipient: 'VaultBank Treasury Dept',
    referenceNumber: 'SYS-INT-202609',
    paymentMethod: 'Internal System Credit',
    location: 'Mumbai Central HQ',
  },
  {
    id: 'TXN-90284075',
    date: '2026-09-05',
    time: '06:40 PM',
    merchant: 'Amazon.in E-Commerce',
    category: 'Shopping',
    amount: 14299.00,
    type: 'debit',
    status: 'Completed',
    account: 'Vault Premier Salary Checking (•••• 4821)',
    senderRecipient: 'Amazon Seller Services',
    referenceNumber: 'AMZ-904810294',
    paymentMethod: 'RuPay Select Card',
    location: 'Bengaluru, KA',
  },
  {
    id: 'TXN-90284061',
    date: '2026-09-01',
    time: '10:00 AM',
    merchant: 'DLF Crest Monthly Maintenance Payment',
    category: 'Utilities',
    amount: 35000.00,
    type: 'debit',
    status: 'Completed',
    account: 'Vault Premier Salary Checking (•••• 4821)',
    senderRecipient: 'DLF Crest Condominium Association',
    referenceNumber: 'NEFT-091481028',
    paymentMethod: 'NEFT Online Bank Transfer',
    location: 'Gurugram, HR',
  },
  {
    id: 'TXN-90284050',
    date: '2026-08-28',
    time: '03:22 PM',
    merchant: 'MakeMyTrip Flight & Hotel Booking',
    category: 'Entertainment',
    amount: 86400.00,
    type: 'debit',
    status: 'Completed',
    account: 'Vault Premier Salary Checking (•••• 4821)',
    senderRecipient: 'MakeMyTrip India Pvt Ltd',
    referenceNumber: 'MMT-90148102',
    paymentMethod: 'Vault Metal Visa Infinite Card',
    location: 'New Delhi, DL',
  }
];

export const mockCards: Card[] = [
  {
    id: 'card-01',
    cardNumber: '•••• •••• •••• 8842',
    cardHolder: 'BAVANA SRUTHI',
    expiry: '11/29',
    cvv: '•••',
    type: 'Visa Infinite',
    cardCategory: 'Credit',
    status: 'Active',
    monthlyLimit: 1000000,
    spentThisMonth: 172840,
    currency: 'INR',
    colorTheme: 'dark-gold',
  },
  {
    id: 'card-02',
    cardNumber: '•••• •••• •••• 3019',
    cardHolder: 'BAVANA SRUTHI',
    expiry: '04/28',
    cvv: '•••',
    type: 'RuPay Select',
    cardCategory: 'Debit',
    status: 'Active',
    monthlyLimit: 500000,
    spentThisMonth: 49299,
    currency: 'INR',
    colorTheme: 'deep-emerald',
  }
];

export const mockStatements: Statement[] = [
  {
    id: 'STM-2026-08',
    period: 'August 2026',
    year: 2026,
    month: 'August',
    accountName: 'Vault Premier Salary Checking',
    accountNumber: '•••• 4821',
    statementDate: '01 Sep 2026',
    fileSize: '1.8 MB',
    status: 'Available',
    closingBalance: 2175495.00,
  },
  {
    id: 'STM-2026-07',
    period: 'July 2026',
    year: 2026,
    month: 'July',
    accountName: 'Vault Premier Salary Checking',
    accountNumber: '•••• 4821',
    statementDate: '01 Aug 2026',
    fileSize: '2.1 MB',
    status: 'Available',
    closingBalance: 1984200.00,
  },
  {
    id: 'STM-2026-06',
    period: 'June 2026',
    year: 2026,
    month: 'June',
    accountName: 'Vault Premier Salary Checking',
    accountNumber: '•••• 4821',
    statementDate: '01 Jul 2026',
    fileSize: '1.6 MB',
    status: 'Available',
    closingBalance: 1845100.00,
  },
  {
    id: 'STM-SAV-2026-08',
    period: 'August 2026',
    year: 2026,
    month: 'August',
    accountName: 'Vault High-Yield Super Savings',
    accountNumber: '•••• 9104',
    statementDate: '01 Sep 2026',
    fileSize: '940 KB',
    status: 'Available',
    closingBalance: 6824018.00,
  }
];

export const mockSupportTickets: SupportTicket[] = [
  {
    id: 'TICK-90812',
    subject: 'International Card Usage Authorization Notification',
    category: 'Cards & Security',
    createdAt: '2026-09-10',
    status: 'Resolved',
    priority: 'Low',
    lastResponse: '2026-09-10 by Priority Desk',
  },
  {
    id: 'TICK-90419',
    subject: 'Request for Form 15G / Interest Certificate FY 2025-26',
    category: 'Tax & Statements',
    createdAt: '2026-08-15',
    status: 'Resolved',
    priority: 'Medium',
    lastResponse: '2026-08-16 by Wealth Desk',
  }
];

export const mockFAQs: FAQItem[] = [
  {
    question: 'How do I raise my daily UPI and IMPS transfer limits?',
    answer: 'You can request a permanent limit enhancement under Profile > Security Settings > Transfer Limits, or submit a request directly through your dedicated Relationship Manager.',
    category: 'Transfers',
  },
  {
    question: 'Are my VaultBank accounts insured by DICGC?',
    answer: 'Yes, all VaultBank customer deposits are fully insured up to ₹5,00,000 per depositor under DICGC guidelines.',
    category: 'Accounts',
  },
  {
    question: 'How do I immediately block a lost or compromised card?',
    answer: 'Navigate to Cards tab and toggle "Card Status" to Locked immediately, or send an SMS "BLOCK <Last 4 Digits>" to 56161.',
    category: 'Security',
  }
];

export const mockInternalServices: InternalService[] = [
  {
    name: 'Vault Core Account Service',
    id: 'srv-core-acc',
    status: 'HEALTHY',
    version: 'v4.12.8-prod',
    endpoint: '/api/v1/core/accounts',
    lastHeartbeat: '2 seconds ago',
    environment: 'production-primary',
    latencyMs: 14,
    uptimePercentage: '99.998%',
  },
  {
    name: 'Transaction Router Engine',
    id: 'srv-txn-router',
    status: 'HEALTHY',
    version: 'v3.8.2-prod',
    endpoint: '/api/transactions',
    lastHeartbeat: '1 second ago',
    environment: 'production-primary',
    latencyMs: 18,
    uptimePercentage: '99.995%',
  },
  {
    name: 'OAuth2 / JWT Auth Guard',
    id: 'srv-auth-guard',
    status: 'HEALTHY',
    version: 'v2.19.1-prod',
    endpoint: '/api/auth/login',
    lastHeartbeat: '3 seconds ago',
    environment: 'production-primary',
    latencyMs: 9,
    uptimePercentage: '100.000%',
  },
  {
    name: 'Customer & KYC Master DB',
    id: 'srv-cust-master',
    status: 'HEALTHY',
    version: 'v5.0.4-prod',
    endpoint: '/api/customers',
    lastHeartbeat: '4 seconds ago',
    environment: 'production-primary',
    latencyMs: 22,
    uptimePercentage: '99.990%',
  },
  {
    name: 'Financial Reporting & Ledger',
    id: 'srv-reporting',
    status: 'HEALTHY',
    version: 'v1.14.0-prod',
    endpoint: '/api/reports',
    lastHeartbeat: '12 seconds ago',
    environment: 'production-primary',
    latencyMs: 45,
    uptimePercentage: '99.980%',
  },
  {
    name: 'Real-Time Fraud Monitoring AI',
    id: 'srv-fraud-ai',
    status: 'HEALTHY',
    version: 'v2.4.0-ml',
    endpoint: '/internal/services/fraud',
    lastHeartbeat: '5 seconds ago',
    environment: 'production-primary',
    latencyMs: 31,
    uptimePercentage: '99.999%',
  }
];

export const mockSystemDebugInfo: SystemDebugInfo = {
  applicationStatus: 'Operational (Cluster Grade A+)',
  serverHealth: 'Optimal (Load Average 0.24, 0.18, 0.15)',
  databaseStatus: 'PostgreSQL Active-Active Primary Node 01 Connected',
  redisCluster: 'Redis Sentinel Enterprise - 6/6 Nodes Synced',
  vaultVersion: 'VaultBank Enterprise Kernel v6.4.1-patch3',
  activeSessions: 14208,
  environment: 'production-asia-south1 (Mumbai)',
  uptime: '148 days, 18 hours, 32 minutes',
  cpuUsage: '12.4%',
  memoryUsage: '34.2 / 128.0 GB RAM',
  logsPreview: [
    {
      timestamp: '2026-09-16T10:14:02Z',
      level: 'INFO',
      module: 'AUTH_MODULE',
      message: 'User session initialized successfully for CUST_ID: VB-8940192 via SSL/TLS 1.3'
    },
    {
      timestamp: '2026-09-16T10:11:45Z',
      level: 'INFO',
      module: 'TXN_ROUTER',
      message: 'Batch processing completed: 4,892 NEFT clearing instructions processed.'
    },
    {
      timestamp: '2026-09-16T10:05:12Z',
      level: 'DEBUG',
      module: 'SECURITY_AUDIT',
      message: 'HMAC signature verification succeeded for payload checksum VB_PROD_58291'
    },
    {
      timestamp: '2026-09-16T09:59:30Z',
      level: 'WARN',
      module: 'RATE_LIMITER',
      message: 'Rate throttle advisory on endpoint /api/auth/login from CIDR 185.220.101.0/24'
    }
  ]
};

// Indian Currency Formatter helper
export function formatINR(amount: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 2,
    minimumFractionDigits: 2,
  }).format(amount);
}
